name = "GKMtest"
uuid = "f0a7beec-ce01-462c-9058-91af0b9134dc"
authors = ["Giosuè Muratore <muratore.g.e@gmail.com >"]
version = "0.1.0"

[deps]
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
Oscar = "1.2.2"
