name = "GKMtest"
uuid = "f0a7beec-ce01-462c-9058-91af0b9134dc"
authors = ["Giosuè Muratore <muratore.g.e@gmail.com >"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
Combinatorics = "1.0.2"
Oscar = "1.2.2"
